version: '3.8'

services:
  frontend:
    build:
      context: ./angular_query_system  # Point to the frontend directory
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "80:80"
    networks:
      - query_system_network

  backend:
    build:
      context: ./query_system  # Point to the backend directory
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "8000:8000"
    networks:
      - query_system_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - query_system_network

networks:
  query_system_network:
    driver: bridge
