version: '3.8'

services:
  backend:
    build: ./query_system
    container_name: django-backend
    restart: always
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./query_system:/app
    

  frontend:
    build: ./angular-query-system
    container_name: angular-frontend
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
