version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "80:80"
    networks:
      - query_system_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "8000:8000"
    networks:
      - query_system_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/ngnix.config:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - query_system_network

networks:
  query_system_network:
    driver: bridge
