name: Docker Compose CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/query_system:qs-django-backend ./query_system
          docker push ${{ secrets.DOCKER_USERNAME }}/query_system:qs-django-backend

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/query_system:qs-angular-frontend ./angular_query_system
          docker push ${{ secrets.DOCKER_USERNAME }}/query_system:qs-angular-frontend

      - name: Build and Push Nginx
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/query_system:qs-nginx-proxy ./nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/query_system:qs-nginx-proxy

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Pull latest images
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/query_system:qs-django-backend
          docker pull ${{ secrets.DOCKER_USERNAME }}/query_system:qs-angular-frontend
          docker pull ${{ secrets.DOCKER_USERNAME }}/query_system:qs-nginx-proxy

      - name: Deploy with Docker Compose
        run: |
          docker-compose up -d
