name: Docker Compose CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        run: |
          docker build -t django-backend ./query_system
          docker tag django-backend:latest ${{ secrets.DOCKER_USERNAME }}/query_system:qs-django-backend
          docker push ${{ secrets.DOCKER_USERNAME }}/query_system:qs-django-backend

      - name: Build and Push Frontend
        run: |
          docker build -t angular-frontend ./angular_query_system
          docker tag angular-frontend:latest ${{ secrets.DOCKER_USERNAME }}/query_system:qs-angular-frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/query_system:qs-angular-frontend

      - name: Build and Push Nginx
        run: |
          docker-compose build nginx
          docker tag nginx-proxy:latest ${{ secrets.DOCKER_USERNAME }}/query_system:qs-nginx-proxy
          docker push ${{ secrets.DOCKER_USERNAME }}/query_system:qs-nginx-proxy

